### ISSUE TITLE
How to make depth estimation consistence for a sequence of images?

### ISSUE THREAD

**Issue by angrysword** [intel-isl/DPT#21]
Thanks for the great works. I just want to get some idea from you. 

Here is: I am running a robot move forward to a chair. I get one frame image per every half seconds. then detect the depth estimation by  the dpt nyu model provided  between robot and chair. The depth suppose to become smaller and smaller. but the actual result does not like that. 

For the sample images, It works like below. metric as meter. it is absolute depth. Leve is meter
![meter](https://user-images.githubusercontent.com/3065257/118544510-58110b00-b70a-11eb-8a62-894a4b28057a.JPG)

There are three reasons I guess lead something wrong.

1. even people hard to see the difference between image 1 and 2. how does the computer know.
2.  thanks @nicolasugrinovic.   It is absolute value as meter show above.  so this point does not make any sense. "It is  relative metric for every time. so not work well cross a sequence of images."
3. Image 4 and 5 is barely have any other reference. so it barely works.

Here are the question:

1. Any suggestion or reference paper I can take a look to work on depth along with a sequence of image?

Thank you very much! 

![im2](https://user-images.githubusercontent.com/3065257/118318439-40d5e180-b4ae-11eb-9cf1-52ea563321db.jpg)
![im3](https://user-images.githubusercontent.com/3065257/118318442-416e7800-b4ae-11eb-849f-d003fd02f38b.jpg)
![im4](https://user-images.githubusercontent.com/3065257/118318443-416e7800-b4ae-11eb-8e29-25b1efcfb816.jpg)
![im5](https://user-images.githubusercontent.com/3065257/118318444-416e7800-b4ae-11eb-8fa8-17377136d3f5.jpg)
![im6](https://user-images.githubusercontent.com/3065257/118318447-42070e80-b4ae-11eb-8341-3847bc1e2b36.jpg)

**Comment by ranftlr** [comment]
Your sequence is extremely challenging, you explain quite well why things might not work optimally. Here is a very recent paper that integrates multiple images which I really liked and might serve as a good starting point: https://arxiv.org/pdf/2104.14540.pdf

**Comment by angrysword** [comment]
thanks for the suggestion. I will take a look the paper to see what I can get from there. I am currently trying to use some other dataset with lidar distance to see if it works.

**Comment by ranftlr** [comment]
For 1: Yes, on NYU images the NYU model should give you absolute depth. Likewise for the KITTI model. For images that differ in the intrinsic parameters from the training camera, it will not quite be absolute depth but it should be consistent (modulo failure cases like the ones shown in initial post).

For 2: For the standard model, the output range is essentially arbitrary per image. The only constraint is that the output is non-negative (I'm thus a bit puzzled by the minimum in your second example, can you tell me at which point you are grabbing the output?) The reason is that the loss that is used for training is zero or small as long as the relative depth relations are correctly fulfilled. The loss of a prediction p is the same as the loss of a prediction a*p + b. Additionally we don't set a maximum output (as we found that this can impede training). So nothing is telling the model to keep its outputs in a certain range. This information is simply lost. What we gain by sacrificing this information is a better behaved training problem when scaling training across very diverse datasets and cameras.

From my experience, it seems though that for a given camera and a a given scene the ranges remain roughly constant as long as there is not too much change in content. However there is no guarantee for that and the scale usually drifts quite a bit.

**Comment by nicolasugrinovic** [comment]
Hi, thanks for the prompt answer!

I take the prediction for the run.py code from the updated MiDasv2 repo. Line [123](https://github.com/intel-isl/MiDaS/blob/fad548fcc3036eb527a7ccc96c47173441b4db37/run.py#L123), so this is before you convert to 16bits resolution and save the depth info. Some more examples give me negative output as well. If you are curious as to where this happens in the image, here is an example. In this image this happens in the change from the person's contour and the sky. 

![image](https://user-images.githubusercontent.com/25443240/119037621-8284f180-b9b2-11eb-9e7a-8ac7ea186f28.png)

**Comment by ranftlr** [comment]
Thanks for pointing this out, was able to reproduce. Negative values seem to happen because of the bicubic upsampling. I never noticed this before. So my statement above about the output being non-negative is only true when the upsampling method is guaranteed to not produce negative values. 

Yes, you generally want to treat the prediction like you would treat a disparity. See #19 for sample reprojection code.

**Comment by nicolasugrinovic** [comment]
Great, thanks!
Glad you could reproduce and find the cause of it.

**Comment by andy500** [comment]
l find using the model_type dpt_hybrid_nyu reduces the flickering effects  ranftlr for create depth maps good code you have created thanks for the code ranftlr
